### 404 root
GET http://localhost:3333


### 404 auth
GET http://localhost:3333/auth

### Signout
POST http://localhost:3333/auth/signout

### create user
POST http://localhost:3333/auth/signup
Content-Type: application/json

{
  "email": "sayuri.mendse@gmail.com",
  "password": "67890",
  "dummyProp": "dummyProp"
}

### sign in user
POST http://localhost:3333/auth/signin
Content-Type: application/json

{
  "email": "gaurav.mendse@gmail.com",
  "password": "12345",
  "dummyProp": "dummyProp"
}

### Get user info from Session.userId
GET http://localhost:3333/auth/whoami

### find user by ID
GET http://localhost:3333/auth/6

### get user by ID
GET http://localhost:3333/auth?id=2

### get user by email
GET http://localhost:3333/auth?email=gaurav.mendse@gmail.com

### update user by ID
PATCH http://localhost:3333/auth/5
Content-Type: application/json

{
  "password": "kucchaPassword5",
  "dummy": "dummy prop value",
  "id": 5
}

### remove user
DELETE  http://localhost:3333/auth/1
