### 404 root
GET http://localhost:3333


### 404 auth
GET http://localhost:3333/auth

### Signout
POST http://localhost:3333/auth/signout

### Get user info from Session.userId
GET http://localhost:3333/auth/whoami

### create user
POST http://localhost:3333/auth/signup
Content-Type: application/json

{
  "email": "sayuri.mendse@gmail.com",
  "password": "67890",
  "dummyProp": "dummyProp"
}

### sign in user
POST http://localhost:3333/auth/signin
Content-Type: application/json

{
  "email": "gaurav.mendse@gmail.com",
  "password": "12345",
  "dummyProp": "dummyProp"
}



### find user by ID
GET http://localhost:3333/auth/9

### get user by ID
GET http://localhost:3333/auth?id=8

### get user by email
GET http://localhost:3333/auth?email=gaurav.mendse@gmail.com

### update user by ID
PATCH http://localhost:3333/auth/5
Content-Type: application/json

{
  "password": "kucchaPassword5",
  "dummy": "dummy prop value",
  "id": 5
}

### remove user
DELETE  http://localhost:3333/auth/8


### create report
POST http://localhost:3333/reports
Content-Type: application/json

{
  "price": 600000,
  "currency": "INR",
  "make": "Hyundai",
  "model": "Creta",
  "year": 1930,
  "city": "Nagpur",
  "country": "India",
  "mileage": 56000
}
